-- MySQL Script generated by MySQL Workbench
-- Wed Jun 19 14:28:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tagshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tagshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tagshop` DEFAULT CHARACTER SET utf8 ;
USE `tagshop` ;

-- -----------------------------------------------------
-- Table `tagshop`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Users` (
  `Userid` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(1000) NOT NULL,
  `Enabled` TINYINT NULL,
  `Email` VARCHAR(50) NULL,
  `Phone` VARCHAR(20) NULL,
  `CreateDate` DATE NULL,
  `UpdateDate` DATE NULL,
  PRIMARY KEY (`Userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`Shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Shops` (
  `ShopId` VARCHAR(50) NOT NULL,
  `Userid` VARCHAR(50) NOT NULL,
  `CorporateName` VARCHAR(100) NULL,
  `CorporateRegisterNumber` VARCHAR(20) NULL,
  `BrandName` VARCHAR(100) NULL,
  `Phone` VARCHAR(50) NULL,
  `Enabled` TINYINT NULL,
  `BankCode` VARCHAR(50) NULL,
  `BankAccount` VARCHAR(50) NULL,
  `CreateDate` DATE NULL,
  `UpdateDate` DATE NULL,
  PRIMARY KEY (`ShopId`, `Userid`),
  INDEX `fk_Shops_Users1_idx` (`Userid` ASC) VISIBLE,
  CONSTRAINT `fk_Shops_Users1`
    FOREIGN KEY (`Userid`)
    REFERENCES `instashop`.`Users` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Products` (
  `ProductId` BIGINT AUTO_INCREMENT,
  `Title` VARCHAR(200) NULL,
  `Description` LONGTEXT NULL,
  `Price` DOUBLE NULL,
  `PhotoFile` VARCHAR(100) NULL,
  `SmallCategoryCode` VARCHAR(9) NULL,
  'MainColor' VARCHAR(50) NULL,
  `CreateDate` DATE NULL,
  `UpdateDate` DATE NULL,
  `ShopId` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ProductId`),
  INDEX `fk_Products_Shop1_idx` (`ShopId` ASC) ,
  CONSTRAINT `fk_Products_Shop1`
    FOREIGN KEY (`ShopId`)
    REFERENCES `tagshop`.`Shops` (`ShopId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Profile` (
  `Userid` VARCHAR(50) NOT NULL,
  `Introduction` VARCHAR(2000) NULL,
  `Website` VARCHAR(100) NULL,
  `PhotoName` VARCHAR(50) NULL,
  `RecipientName` VARCHAR(100) NULL,
  `Address1` VARCHAR(100) NULL,
  `Address2` VARCHAR(100) NULL,
  `PostalCode` VARCHAR(50) NULL,
  `CountryCode` VARCHAR(3) NULL,
  `DeliveryMemo` VARCHAR(1000) NULL,
  `CardCompanyCode` VARCHAR(10) NULL,
  `CardNumber` VARCHAR(16) NULL,
  `CardPeriod` VARCHAR(4) NULL,
  `Cvc` VARCHAR(3) NULL,
  `CardPassword` VARCHAR(2) NULL,
  `Point` INT NULL,
  `RepostNumber` INT NULL,
  INDEX `fk_Profile_Users1_idx` (`Userid` ASC),
  CONSTRAINT `fk_Profile_Users1`
    FOREIGN KEY (`Userid`)
    REFERENCES `instashop`.`Users` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

-- -----------------------------------------------------
-- Table `tagshop`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Photo` (
  `PhotoId` BIGINT AUTO_INCREMENT,
  `FileName` VARCHAR(50) NULL,
  `Description` VARCHAR(500) NULL,
  `RefPhotoId` BIGINT NULL,
  `RefProductId` BIGINT NULL,
  `CreateDate` DATE NULL,
  `UpdateDate` DATE NULL,
  `Userid` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`PhotoId`),
  INDEX `fk_Photo_Users1_idx` (`Userid` ASC) ,
  CONSTRAINT `fk_Photo_Users1`
    FOREIGN KEY (`Userid`)
    REFERENCES `tagshop`.`Users` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`Following`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Following` (
  `FollowingId` VARCHAR(50) NOT NULL,
  `UsersUserid` VARCHAR(50) NOT NULL,
  INDEX `fk_Following_Users1_idx` (`UsersUserid` ASC) ,
  PRIMARY KEY (`FollowingId`, `UsersUserid`),
  CONSTRAINT `fk_Following_Users1`
    FOREIGN KEY (`UsersUserid`)
    REFERENCES `tagshop`.`Users` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`Follower`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Follower` (
  `FollowerId` VARCHAR(50) NOT NULL,
  `UsersUserid` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`FollowerId`, `UsersUserid`),
  INDEX `fk_Follower_Users1_idx` (`UsersUserid` ASC) ,
  CONSTRAINT `fk_Follower_Users1`
    FOREIGN KEY (`UsersUserid`)
    REFERENCES `tagshop`.`Users` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Likes` (
  `PhotoId` BIGINT NOT NULL,
  `UsersUserid` VARCHAR(50) NOT NULL,
  `LikeYn` TINYINT NULL,
  `BuyYn` TINYINT NULL,
  INDEX `fk_Likes_Photo1_idx` (`PhotoId` ASC) ,
  INDEX `fk_Likes_Users1_idx` (`UsersUserid` ASC) ,
  PRIMARY KEY (`PhotoId`, `UsersUserid`),
  CONSTRAINT `fk_Likes_Photo1`
    FOREIGN KEY (`PhotoId`)
    REFERENCES `tagshop`.`Photo` (`PhotoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Likes_Users1`
    FOREIGN KEY (`UsersUserid`)
    REFERENCES `tagshop`.`Users` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Comments` (
  `CommentsId` BIGINT NOT NULL DEFAULT AUTO_INCREMENT,
  `Comments` VARCHAR(200) NULL,
  `BuyYn` TINYINT NULL,
  `CreateDate` DATE NULL,
  `UpdateDate` DATE NULL,
  `PhotoId` BIGINT NOT NULL,
  `UsersUserid` VARCHAR(50) NOT NULL,
  INDEX `fk_Comments_Photo1_idx` (`PhotoId` ASC) VISIBLE,
  INDEX `fk_Comments_Users1_idx` (`UsersUserid` ASC) VISIBLE,
  PRIMARY KEY (`CommentsId`),
  CONSTRAINT `fk_Comments_Photo1`
    FOREIGN KEY (`PhotoId`)
    REFERENCES `instashop`.`Photo` (`PhotoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Users1`
    FOREIGN KEY (`UsersUserid`)
    REFERENCES `instashop`.`Users` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`TagsLocale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`TagsLocale` (
  `TagsId` BIGINT AUTO_INCREMENT,
  `TagsNameEn` VARCHAR(100) NULL,
  `TagsNameEs` VARCHAR(100) NULL,
  `TagsNameZh` VARCHAR(100) NULL,
  `TagsNameHi` VARCHAR(100) NULL,
  `TagsNameJa` VARCHAR(100) NULL,
  `TagsNameRu` VARCHAR(100) NULL,
  `TagsNamePt` VARCHAR(100) NULL,
  `TagsNameKo` VARCHAR(100) NULL,
  PRIMARY KEY (`TagsId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`PhotoTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`PhotoTags` (
  `PhotoId` BIGINT NOT NULL,
  `TagsId` BIGINT NOT NULL,
  INDEX `fk_Tags_Photo1_idx` (`PhotoId` ASC) ,
  INDEX `fk_Tags_TagsLocale1_idx` (`TagsId` ASC) ,
  CONSTRAINT `fk_Tags_Photo1`
    FOREIGN KEY (`PhotoId`)
    REFERENCES `tagshop`.`Photo` (`PhotoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tags_TagsLocale1`
    FOREIGN KEY (`TagsId`)
    REFERENCES `tagshop`.`TagsLocale` (`TagsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`TagsPriceHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`TagsPriceHistory` (
  `BaseDate` VARCHAR(8) NOT NULL,
  `TagsId` BIGINT NOT NULL,
  `CurrencyCode` VARCHAR(3) NULL,
  `Rank` INT NULL,
  `Price` DOUBLE NULL,
  INDEX `fk_TagsPriceHistory_TagsLocale1_idx` (`TagsId` ASC) ,
  PRIMARY KEY (`BaseDate`, `TagsId`, `CurrencyCode`),
  CONSTRAINT `fk_TagsPriceHistory_TagsLocale1`
    FOREIGN KEY (`TagsId`)
    REFERENCES `tagshop`.`TagsLocale` (`TagsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`Baskets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Baskets` (
  `BasketId` BIGINT AUTO_INCREMENT,
  `DeliveryFee` DOUBLE NULL,
  `UsedPoint` DOUBLE NULL,
  `PayTypeCode` VARCHAR(10) NULL,
  `CreateDate` DATE NULL,
  `UpdateDate` DATE NULL,
  `Userid` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`BasketId`),
  INDEX `fk_Baskets_Users1_idx` (`Userid` ASC) ,
  CONSTRAINT `fk_Baskets_Users1`
    FOREIGN KEY (`Userid`)
    REFERENCES `tagshop`.`Users` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;



-- -----------------------------------------------------
-- Table `tagshop`.`ProductItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`ProductItem` (
  `ProductItemId` BIGINT  AUTO_INCREMENT,,
  `ProductName` VARCHAR(100) NULL,
  `UnitPrice` DOUBLE NULL,
  `ProductId` BIGINT NOT NULL,
  PRIMARY KEY (`ProductItemId`),
  INDEX `fk_ProductItem_Products1_idx` (`ProductId` ASC) ,
  CONSTRAINT `fk_ProductItem_Products1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `tagshop`.`Products` (`ProductId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`BuyItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`BuyItems` (
  `BuyItemsId` BIGINT AUTO_INCREMENT,
  `UnitPrice` DOUBLE NULL,
  `Quantity` INT NULL,
  `OrderStatusCode` VARCHAR(10) NULL,
  `BasketId` BIGINT NOT NULL,
  `ProductItemId` BIGINT NOT NULL,
  PRIMARY KEY (`BuyItemsId`),
  INDEX `fk_BuyItems_Baskets1_idx` (`BasketId` ASC) ,
  INDEX `fk_BuyItems_ProductItem1_idx` (`ProductItemId` ASC) ,
  CONSTRAINT `fk_BuyItems_Baskets1`
    FOREIGN KEY (`BasketId`)
    REFERENCES `tagshop`.`Baskets` (`BasketId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BuyItems_ProductItem1`
    FOREIGN KEY (`ProductItemId`)
    REFERENCES `tagshop`.`ProductItem` (`ProductItemId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;



-- -----------------------------------------------------
-- Table `tagshop`.`Options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Options` (
  `OptionId` BIGINT AUTO_INCREMENT,
  `OptionType` VARCHAR(50) NULL,
  `OptionCode` VARCHAR(50) NULL,
  `ProductItemId` INT NOT NULL,
  PRIMARY KEY (`OptionId`),
  INDEX `fk_Options_ProductItem1_idx` (`ProductItemId` ASC) ,
  CONSTRAINT `fk_Options_ProductItem1`
    FOREIGN KEY (`ProductItemId`)
    REFERENCES `tagshop`.`ProductItem` (`ProductItemId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;



-- -----------------------------------------------------
-- Table `tagshop`.`SelectedOption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`SelectedOption` (
  `OptionId` BIGINT AUTO_INCREMENT,
  `OptionType` VARCHAR(5) NULL,
  `OptionCode` VARCHAR(50) NULL,
  `BuyItemsId` BIGINT NOT NULL,
  PRIMARY KEY (`OptionId`),
  INDEX `fk_SelectedOption_BuyItems1_idx` (`BuyItemsId` ASC) ,
  CONSTRAINT `fk_SelectedOption_BuyItems1`
    FOREIGN KEY (`BuyItemsId`)
    REFERENCES `tagshop`.`BuyItems` (`BuyItemsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;



-- -----------------------------------------------------
-- Table `tagshop`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Roles` (
  `Authority` VARCHAR(50) NOT NULL,
  `RoleName` VARCHAR(200) NULL,
  `CreateDate` DATE NULL,
  `UpdateDate` DATE NULL,
  PRIMARY KEY (`Authority`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;



-- -----------------------------------------------------
-- Table `tagshop`.`Authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Authorities` (
  `Userid` VARCHAR(50) NOT NULL,
  `Authority` VARCHAR(50) NOT NULL,
  INDEX `fk_Authorities_Users1_idx` (`Userid` ASC) ,
  INDEX `fk_Authorities_Roles1_idx` (`Authority` ASC) ,
  CONSTRAINT `fk_Authorities_Users1`
    FOREIGN KEY (`Userid`)
    REFERENCES `tagshop`.`Users` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Authorities_Roles1`
    FOREIGN KEY (`Authority`)
    REFERENCES `tagshop`.`Roles` (`Authority`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Categories` (
  `LargeCategoryCode` VARCHAR(3) NOT NULL,
  `LargeCategoryName` VARCHAR(100) NULL,
  `MidCategoryCode` VARCHAR(6) NOT NULL,
  `MidCategoryName` VARCHAR(100) NULL,
  `SmallCategoryCode` VARCHAR(9) NULL,
  `SmallCategoryName` VARCHAR(100) NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`ProductTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`ProductTags` (
  `TagsId` BIGINT NOT NULL,
  `ProductId` BIGINT NOT NULL,
  INDEX `fk_Tags_TagsLocale1_idx` (`TagsId` ASC) ,
  INDEX `fk_ProductTags_Products1_idx` (`ProductId` ASC) ,
  CONSTRAINT `fk_Tags_TagsLocale10`
    FOREIGN KEY (`TagsId`)
    REFERENCES `tagshop`.`TagsLocale` (`TagsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductTags_Products1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `tagshop`.`Products` (`ProductId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`Code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Code` (
  `ClassCode` VARCHAR(10) NOT NULL,
  `ClassName` VARCHAR(50) NULL,
  `Code` VARCHAR(10) NOT NULL,
  `CodeName` VARCHAR(50) NULL,
  `Orders` INT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`Reposts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`Reposts` (
  `PhotoId` BIGINT NOT NULL,
  `UsersUserid` VARCHAR(50) NOT NULL,
  `BuyYn` TINYINT NULL,
  INDEX `fk_Reposts_Users1_idx` (`UsersUserid` ASC) VISIBLE,
  INDEX `fk_Reposts_Photo1_idx` (`PhotoId` ASC) VISIBLE,
  PRIMARY KEY (`PhotoId`, `UsersUserid`),
  CONSTRAINT `fk_Reposts_Users1`
    FOREIGN KEY (`UsersUserid`)
    REFERENCES `instashop`.`Users` (`Userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reposts_Photo1`
    FOREIGN KEY (`PhotoId`)
    REFERENCES `instashop`.`Photo` (`PhotoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tagshop`.`SelectedCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tagshop`.`SelectedCategories` (
  `ShopId` VARCHAR(50) NOT NULL,
  `MidCategoryCode` VARCHAR(6) NOT NULL,
  INDEX `fk_SelectedCategories_Shops1_idx` (`ShopId` ASC) ,
  CONSTRAINT `fk_SelectedCategories_Shops1`
    FOREIGN KEY (`ShopId`)
    REFERENCES `tagshop`.`Shops` (`ShopId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
